name: domo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  crypto: ^3.0.6
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  geolocator: ^13.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  liquid_swipe: ^3.1.0
  lucide_icons: ^0.257.0
  pin_code_fields: ^8.0.1
  shadcn_ui: ^0.14.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  google_maps_flutter: ^2.3.1
  geocoding: ^2.1.1
  dio: ^5.7.0
  flutter_polyline_points: ^2.1.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  firebase_app_check: ^0.3.1+6
  table_calendar: ^3.1.3
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/onboard/
    - assets/images/theme/
