// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAK5cLnqO1vPwmSuIhhszzPXi7EfYCskI',
    appId: '1:862849277685:web:0cb96ca435d95a2aa56fbc',
    messagingSenderId: '862849277685',
    projectId: 'domo-2bec7',
    authDomain: 'domo-2bec7.firebaseapp.com',
    storageBucket: 'domo-2bec7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNu-qygoYHrvwmwKXxrCxievmS16vtD90',
    appId: '1:862849277685:android:1a2b09b35214c8b1a56fbc',
    messagingSenderId: '862849277685',
    projectId: 'domo-2bec7',
    storageBucket: 'domo-2bec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hLL4z8ph6PySMI7HK94uGx-8wC6bAqM',
    appId: '1:862849277685:ios:845097285a474606a56fbc',
    messagingSenderId: '862849277685',
    projectId: 'domo-2bec7',
    storageBucket: 'domo-2bec7.appspot.com',
    iosBundleId: 'com.example.domo',
  );

}